# Project information
site_name: "ML REPA Library: MLOps and ML Engineering Solutions for Success"
site_url: https://mlrepa.github.io/mlrepa-library/
site_author: Mikhail Rozhkov
site_description: >-
  This library is dedicated to providing the most up-to-date and relevant information, tutorials, and solutions to help you succeed in your machine learning projects.

# Repository
repo_name: ML REPA Library
repo_url: https://github.com/mlrepa/mlrepa-library

# Copyright
copyright: Copyright &copy; 2023 Machine Learning REPA

theme: 
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
      primary: deep purple
      accent: cyan
    - scheme: slate 
      toggle:
        icon: material/brightness-6
        name: Switch to light mode    
      primary: deep purple
      accent: teal
  logo: assets/logo.png
  favicon: assets/images/favicon.png

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true 
  

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - social
  - tags

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mlrepa 
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mlrepa  
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/9320089/

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js


# Page tree
nav:
  - ML REPA: 
    - index.md
    # - Community: ''
    - Contributors Guide: community/contribution-guide.md
    - Author Guide: community/author-guide.md
    - Roadmap: repa/roadmap.md

  - Tutorials: # tool features
    - Get Started: 
      - project/index.md
      - Command Line Interface (CLI): project/1-cli-get-started.md
      - Get started with Git: project/1-git-get-started.md
      - Basic Git commands: project/2-git-basics.md
      - Git workflow - Remote: project/3-git-remote.md
      - Git workflow - Fork: project/4-git-fork.md
      - Virtual Environments and Package Managers: project/project-2-virtualenv.md
      - Docker: project/project-4-docker.md
   
    - DVC:
      - Get Started with DVC: dvc/dvc-1-get-started.md
      - Data Versioning with DVC: dvc/dvc-2-data-versioning.md
      - Automate ML experiments with DVC: dvc/dvc-3-automate-experiments.md

  # - REPA: # Review REPA principles 
    # - Reliable & Reproducible ML:
      # - Reproducible ML: '' 
      # - Data Versioninig: '' 
      # - Testing and Monitoring: '' 
    # - Experiments Management:
      # - Metrics tracking: ''
    # - Pipelines: '' 
    # - Automation: ''  
      
  - Production ML and MLOps: # Production techniques and patterns 
    - mlops/index.md
    - Overview: 
      - Intro to Production ML and MLOps: mlops/mlops-0-overview.md
      - ML Systems Architecture Design: mlops/mlops-1-system-architecture.md
      - Web Services, Frameworks, APIs: mlops/mlops-2-api-frameworks.md
    # - Metrics tracking and Experiment: ''
    # - CI/CD for Machine Learning: ''
    # - Monitoring and Observability: ''

  # - Solutions: # industrial use cases and integrations 
  #   - Batch scoring: ''
  #   - Computer Vision: ''
  #   - NLP: ''
  #   - LLM: ''
  #   - Instruct Models: GPT...

  - Resources:
    - Projects: resources/projects.md
    - Resources: resources/resources.md

  # HIDDEN PAGES - DO NOT UNCOMMENT
  # - School: 
  #   - git-101: school/git-101-assignment-1.md

